---
abstract: 'Provides an Olson timezone database interface'
author:
  - 'David Dick <ddick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Fcntl: '0'
  File::Temp: '0'
  HTTP::Request: '0'
  LWP::Protocol::https: '6.06'
  LWP::UserAgent: '0'
  Taint::Util: '0'
  Test::More: '0'
  Time::Local: '0'
  XML::LibXML: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.46, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-Zone-Olson
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Config: '0'
  Digest::SHA: '0'
  DirHandle: '0'
  Encode: '0'
  English: '0'
  File::Find: '0'
  File::Spec: '0'
  FileHandle: '0'
  POSIX: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
version: '0.39'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
